name: actions-app1
on: [workflow_dispatch]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'app1-release0'
          path: 'cfuntion/app1'
      - run: ls
      - run: cat cfuntion/app1/readme.txt
