name: actions-app1
on: [workflow_dispatch]
jobs:
  list-info:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ./cfuntion/app1/
    defaults:
      run:
        working-directory: ./cfuntion/app1/
    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'app1-release3'
          #path: 'cfuntion/app1'
      - run: ls 
      - run: tree
      - run: cat readme.txt
