name: actions-app1
on: 
  workflow_dispatch:
    inputs:
      commit_ref:
        description: 'Insert the SHA or Tag of the commit'     
        required: true
        default: 'master'
jobs:
  list-info:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ./cfuntion/app1/
    defaults:
      run:
        working-directory: ./cfuntion/app1/
    steps:
      - uses: actions/checkout@v3
        with:
          #ref: 'app1-release3'
          ref: '${{ github.event.inputs.commit_ref }}'
      - run: ls 
      - run: tree
      - run: cat readme.txt
      - uses: actions/setup-python@v3
        with:
          python-version: '3.9'
          cache: 'pip'
      - run: pip install -r requirements.txt
      - run: python3 -m pytest

